### PR TITLE
Allows keepalive on client to be configured and to be installed gems versions to be locked

### PR DESCRIPTION
**Pull request by LarsFronius**
Both implementations are meant to be backward compatible.

### CODE REVIEW

**Comment by powellchristoph** [comment]
Thanks for the PR! I like the added functionality, but could the pillar structure be tweaked slightly?

Instead of
```
install_gems:
    - name: aws-sdk
      version: 2.2.6
```
could you do
```
install_gems:
    - aws-sdk: 2.2.6
    - timeout
```
-

**Comment by puneetk** [comment]
I prefer the readability of whats @LarsFronius implemented

```
install_gems_obfuscated:
    - aws-sdk: 2.2.6
    - timeout

install_gems:
    - 
      name: aws-sdk
      version: 2.2.6
    - timeout
```

```
{
  "install_gems": [
    {
      "version": "2.2.6", 
      "name": "aws-sdk"
    }, 
    "timeout"
  ], 
  "install_gems_obfuscated": [
    {
      "aws-sdk": "2.2.6"
    }, 
    "timeout"
  ]
}
```

**Comment by hsatterwhite-transloc** [comment]
So is the preferred convention going to be what @powellchristoph proposed? This would be a great pull request to have approved and merged in to master. I for one am in favor of @powellchristoph's convention. It simplifies the pillar data by not having you add yet another level of data.

**Comment by envintus** [comment]
So is the preferred convention going to be what @powellchristoph proposed? This would be a great pull request to have approved and merged in to master.

I for one am in favor of @powellchristoph's convention. It simplifies the pillar data by not having you add yet another level of data.

**Comment by gravyboat** [comment]
Could you please rebase @LarsFronius? I'm not sure how this got missed, sorry about that.

**Comment by envintus** [comment]
Thanks for the quick response!

**Comment by envintus** [comment]
@puneetk, @powellchristoph and @LarsFronius 

Is there any more interest in determining which convention to move forward with? Or could we have this PR rebased and merged as is? This would be a very useful feature regardless of the convention chosen. Just my two cents, but I also like @LarsFronius proposal to include ``version`` as a separate attribute.

**Comment by babilen** [comment]
How about:

```
install_gems:
    - aws-sdk: 
      version: 2.2.6
    - timeout
```

This is readable and allows for simple conditional evaluation.

**Comment by powellchristoph** [comment]
Either way works for me.

**Comment by envintus** [comment]
Added changes to master.

**Pull request closed without merging**
